# Site settings
title: Oliver Cardoza
email: me@olivercardoza.com
description: "still in development"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://olivercardoza.com" # the base hostname & protocol for your site
twitter_username: OliverCardoza
github_username:  OliverCardoza

# Build settings
exclude: [
  .gitignore,
  CNAME,
  Gemfile,
  Gemfile.lock,
  README.md,
  # Required see: https://github.com/jekyll/jekyll/issues/5267
  vendor
]
markdown: kramdown
highlighter: rouge
timezone: Canada/Eastern

# Google services
google_analytics: UA-79649328-1
